### ISSUE TITLE
require snippet is broken

### ISSUE THREAD

**Issue by omkelderman** [DeLaGuardo/language-iced-coffee-script#3]
instead of me trying to explain it, i'll just show it: https://omk.pics/1/ChKNB.mp4

**Comment by DeLaGuardo** [comment]
Can't reproduce this (1.8.0 atom version)
https://dl.dropboxusercontent.com/s/e1odd86f28h7vrd/41DB085D-FC02-4C4C-B27D-7ECB426144EE-52260-000012B7251109F9.gif?dl=0

**Comment by omkelderman** [comment]
hmm, weird, im also on 1.8.0

I'll try a fresh atom install and see what happens later today (im kinda doing something atm :stuck_out_tongue:)

**Comment by omkelderman** [comment]
oops, i sort of forgot about this....

anyways, did a fresh windows install on a vm, installed atom + only this package, can confirm it works as intended... now lets figure out why on earth it doesnt on my main PC :worried:

**Comment by omkelderman** [comment]
ok, i have no idea, but suddenly it started to work properly again... no clue what fixed it.. Probably some upgrades of random things i probably have done in the meantime...
